export const cartDropdownActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOOGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FORM_CART',
    REDUCE_ITEM: 'REDUCE_ITEM'
}

